### ISSUE TITLE
Build fails on Windows unless cookbooks directory is created ahead of time

### ISSUE THREAD

**Issue by jimshowalter** [ctron/rpm-builder#21]
Was getting https://github.com/ctron/rpm-builder/blob/master/src/main/java/de/dentrassi/rpm/builder/RpmMojo.java#L482.  Creating target/cookbooks and then running mvn install worked.

The mojo seems to assume existence of the directory, or seems to assume it can create files in the directory without first creating the directory if it's not there. Need to call mkdirs on the target directory.

**Comment by ctron** [comment]
I am sorry but I can't really follow what the problem is. I don't know anything about `target/cookbooks` either. Also the location you point to is a generic exception wrapper. I am not sure what the problem is there.

Maybe you can help me understand you context and what the problem is. Which version of the plugin you are using.
